# Generated by Django 5.1.4 on 2025-01-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("water_level", models.FloatField()),
                ("rain", models.BooleanField()),
                ("light", models.BooleanField()),
            ],
        ),
    ]
