# Generated by Django 5.1.4 on 2025-01-10 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 1, 10, 21, 31, 42, 890763, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
