# Generated by Django 5.1.4 on 2025-01-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0002_sensordata_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("max_temperature", models.FloatField(blank=True, null=True)),
                ("min_temperature", models.FloatField(blank=True, null=True)),
                ("max_humidity", models.FloatField(blank=True, null=True)),
                ("min_humidity", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
