# Generated by Django 5.1.4 on 2025-01-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensor", "0003_dailystats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="light",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="rain",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="water_level",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
